repos:
  # Ruff: линтер и форматтер
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff # Линтер
        args: [--fix] # Автоисправление ошибок
      - id: ruff-format # Форматирование кода

  # Mypy: проверка типов
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.10.0
#    hooks:
#      - id: mypy
#        additional_dependencies: []
#        files: ^(services/|tests/|.*\.py$) # Проверяем все Python-файлы

  # Базовые фиксы форматирования
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer # Добавляем пустую строку в конец файла
      - id: trailing-whitespace # Убираем лишние пробелы в конце строк
